import { escapeHtml as e, relativeUrl } from './render.mjs';
export const components = [
  { id: 'explorer', name: 'Explorer', note: 'ファイルとフォルダ' },
  { id: 'spreadsheet', name: 'Spreadsheet', note: 'セルとワークブック' },
  { id: 'core', name: 'Core', note: '共通の型とヘルパー' },
];

export function renderPage(page, pages) {
  const url = target => e(relativeUrl(page.output, target));
  const groups = components.map(component => {
    const children = pages.filter(item => item.component === component.id);
    let previousSection;
    const links = children.map(item => {
      const section = item.section && item.section !== previousSection ? `<li class="nav-section" data-nav-section>${e(item.section)}</li>` : '';
      previousSection = item.section;
      return `${section}<li data-nav-item data-page-id="${e(item.id)}"><a href="${url(item.output)}"${page.id === item.id ? ' aria-current="page"' : ''}>${e(item.title)}</a></li>`;
    }).join('');
    return `<details class="component-nav" data-component="${component.id}"${page.component === component.id || page.id === 'index' ? ' open' : ''}><summary><span>${component.name}</span><span class="component-note">${component.note}</span></summary><ul>${links}</ul></details>`;
  }).join('');
  const headingLinks = page.headings.filter(heading => heading.depth === 2).map(heading => `<li><a href="#${encodeURIComponent(heading.id)}">${e(heading.title)}</a></li>`).join('') + (page.screenshots?.length ? '<li><a href="#operation-screenshots">画面例</a></li>' : '');
  const screenHtml = page.screenshots?.length ? `<section class="screenshots" aria-label="操作画面"><h2 id="operation-screenshots">画面例</h2>${page.screenshots.map(shot => `<figure><a class="screenshot-link" href="${url(shot.src)}" aria-label="${e(shot.alt)}を原寸で開く"><img src="${url(shot.src)}" alt="${e(shot.alt)}" width="${shot.width}" height="${shot.height}" loading="lazy"></a><figcaption>${e(shot.caption)}</figcaption></figure>`).join('')}</section>` : '';
  const sourceLinks = page.sources.map(source => `<a href="https://github.com/sunu-py-jp/LikeX/blob/main/${e(source)}">${e(source.split('/').pop())}</a>`).join(' · ');
  const neighbors = pages.filter(item => item.component === page.component);
  const index = neighbors.findIndex(item => item.id === page.id);
  const previous = neighbors[index - 1], next = neighbors[index + 1];
  const footerNav = page.component ? `<nav class="page-navigation" aria-label="前後のページ">${previous ? `<a href="${url(previous.output)}"><span>前のページ</span>${e(previous.title)}</a>` : '<span></span>'}${next ? `<a href="${url(next.output)}"><span>次のページ</span>${e(next.title)}</a>` : ''}</nav>` : '';
  return `<!doctype html>
<!-- Generated by npm run docs:build. Edit the Markdown guide or page.json. -->
<html lang="ja"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="description" content="${e(page.summary)}"><title>${e(page.title)} | ${page.component ? components.find(c => c.id === page.component).name + ' · ' : ''}LikeX API Docs</title><link rel="stylesheet" href="${url('assets/docs.css')}"><script src="${url('assets/search-index.js')}" defer></script><script src="${url('assets/docs.js')}" defer></script></head>
<body data-page="${e(page.id)}"><a class="skip-link" href="#main">本文へ移動</a>
<header class="site-header"><a class="brand" href="${url('index.html')}"><strong>LikeX</strong><span>API Docs</span></a><span class="header-caption">React components</span><a class="repository-link" href="https://github.com/sunu-py-jp/LikeX">GitHub <span aria-hidden="true">↗</span></a><button class="mobile-menu-button" type="button" aria-expanded="false" aria-controls="sidebar">メニュー</button></header>
<div class="docs-layout"><aside class="sidebar" id="sidebar" aria-label="ドキュメントのメニュー"><div class="search-field"><label for="docs-search">APIを探す</label><div class="search-input-row"><input id="docs-search" type="search" placeholder="例: onSave、コピー" autocomplete="off" spellcheck="false"><kbd>/</kbd></div><p class="search-status" role="status" aria-live="polite" hidden></p></div><nav aria-label="コンポーネントと機能"><a class="overview-link" href="${url('index.html')}"${page.id === 'index' ? ' aria-current="page"' : ''}>はじめに</a>${groups}<p class="search-empty" hidden>一致するページはありません。</p></nav></aside>
<button class="mobile-backdrop" aria-label="メニューを閉じる" hidden></button>
<main id="main" tabindex="-1"><div class="page-topline"><a href="${url('index.html')}">ドキュメント</a>${page.component ? `<span aria-hidden="true">/</span><span>${components.find(c => c.id === page.component).name}</span>` : ''}</div><div class="reading-layout"><article><header class="article-header"><p class="package-name">${page.component ? `@likex/${page.component}` : 'LikeX'}</p><h1>${e(page.title)}</h1><p class="page-summary">${e(page.summary)}</p>${page.screenshots?.length ? '<a class="screen-shortcut" href="#operation-screenshots">画面例を見る ↓</a>' : ''}</header>${page.html}${screenHtml}${footerNav}<footer class="article-footer">編集元: ${sourceLinks}<br>本文は公開APIと利用ガイドから生成しています。</footer></article>${headingLinks ? `<aside class="page-toc" aria-label="このページの見出し"><p>このページ</p><ol>${headingLinks}</ol></aside>` : ''}</div></main></div><p class="copy-status" role="status" aria-live="polite"></p></body></html>\n`;
}
