import test from 'node:test';
import assert from 'node:assert/strict';
import { build } from 'esbuild';
const bundle = await build({ entryPoints: [new URL('../src/model-entry.ts',import.meta.url).pathname], bundle:true, platform:'node',format:'esm',write:false });
const api = await import(`data:text/javascript;base64,${Buffer.from(bundle.outputFiles[0].text+'\n//# sourceURL=diagram-model-test.js').toString('base64')}`);
const { createDiagram, normalizeDiagram, parseDiagram, serializeDiagram, executeDiagramCommands, exportDiagramSvg, getDiagramEdgeGeometry } = api;
const model = () => createDiagram({id:'graph',title:'Process',nodes:[{id:'a',text:'A',x:0,y:0,width:100,height:80},{id:'b',shape:'diamond',text:'B',x:200,y:100,width:120,height:100}],edges:[{id:'edge',sourceId:'a',targetId:'b',label:'Next'}]});
test('model is immutable JSON and serializes identically without changing identifiers',()=>{ const source=model(), json=serializeDiagram(source); assert.equal(serializeDiagram(parseDiagram(json)),json); assert.ok(Object.isFrozen(source.nodes[0])); assert.throws(()=>source.nodes.push({})); assert.equal(source.nodes[0].id,'a'); });
test('atomic batch supports creation, movement, resize, alignment, edges and cascading deletion',()=>{const source=model(), before=serializeDiagram(source);const next=executeDiagramCommands(source,[{type:'node.add',node:{id:'c',x:500,y:400}},{type:'nodes.move',ids:['a','b'],dx:10,dy:20},{type:'node.update',id:'c',patch:{width:200,fill:'#abcdef'}},{type:'nodes.align',ids:['a','b','c'],alignment:'top'},{type:'edge.add',edge:{id:'e2',sourceId:'b',targetId:'c'}}]);assert.ok(next.nodes.every(node=>node.y===20));assert.equal(next.nodes[2].width,200);assert.equal(next.edges.length,2);const removed=executeDiagramCommands(next,{type:'node.remove',ids:['b']});assert.equal(removed.edges.length,0);assert.equal(removed.nodes.length,2);assert.equal(serializeDiagram(source),before);assert.throws(()=>executeDiagramCommands(source,[{type:'node.update',id:'a',patch:{text:'changed'}},{type:'edge.add',edge:{sourceId:'a',targetId:'missing'}}]));assert.equal(serializeDiagram(source),before);});
test('rejects duplicate IDs, invalid references, unsafe colors, malformed versions and coordinates',()=>{const source=model();for(const mutation of [{...source,version:2},{...source,nodes:[source.nodes[0],source.nodes[0]]},{...source,edges:[{...source.edges[0],targetId:'a'}]},{...source,nodes:[{...source.nodes[0],fill:'url(https://bad)'},source.nodes[1]]}])assert.throws(()=>normalizeDiagram(mutation));for(const command of [{type:'nodes.move',ids:['a'],dx:Infinity,dy:0},{type:'node.update',id:'a',patch:{width:0}},{type:'nodes.align',ids:['missing'],alignment:'left'}])assert.throws(()=>executeDiagramCommands(source,command));});
test('SVG escapes content and edge anchors meet node borders',()=>{const source=executeDiagramCommands(model(),[{type:'node.update',id:'a',patch:{text:'<script>alert("x")</script> & text'}},{type:'edge.update',id:'edge',patch:{label:'<unsafe>'}}]);const svg=exportDiagramSvg(source);assert.ok(svg.startsWith('<svg'));assert.ok(!svg.includes('<script>'));assert.ok(!svg.includes('<unsafe>'));assert.ok(svg.includes('&lt;unsafe&gt;'));assert.ok(!svg.includes('foreignObject'));const straight=getDiagramEdgeGeometry({id:'a',shape:'rectangle',x:0,y:0,width:100,height:100},{id:'b',shape:'ellipse',x:200,y:0,width:100,height:100});assert.deepEqual(straight.start,{x:100,y:50});assert.deepEqual(straight.end,{x:200,y:50});});
test('removing a missing ID and updating ID via a patch fail instead of silently corrupting references',()=>{assert.throws(()=>executeDiagramCommands(model(),{type:'node.remove',ids:['missing']}));assert.throws(()=>executeDiagramCommands(model(),{type:'node.update',id:'a',patch:{id:'b'}}));});

test('node and edge ordering preserve relative order, serialize and export consistently, and reject atomically',()=>{
 const source=executeDiagramCommands(model(),[{type:'node.add',node:{id:'c',text:'C'}},{type:'edge.add',edge:{id:'e2',sourceId:'b',targetId:'c',label:'Second'}}]);
 const before=serializeDiagram(source),next=executeDiagramCommands(source,[{type:'nodes.order',ids:['b','a'],position:'front'},{type:'edges.order',ids:['e2'],position:'back'}]);
 assert.deepEqual(next.nodes.map(node=>node.id),['c','a','b']); assert.deepEqual(next.edges.map(edge=>edge.id),['e2','edge']); assert.equal(serializeDiagram(parseDiagram(serializeDiagram(next))),serializeDiagram(next));
 const svg=exportDiagramSvg(next); assert.ok(svg.indexOf('Second')<svg.indexOf('Next')); assert.equal(serializeDiagram(source),before);
 assert.throws(()=>executeDiagramCommands(source,[{type:'nodes.order',ids:['a'],position:'back'},{type:'edges.order',ids:['missing'],position:'front'}]));
 assert.throws(()=>executeDiagramCommands(source,{type:'nodes.order',ids:['a'],position:'sideways'}));assert.equal(serializeDiagram(source),before);
});
