import test from 'node:test';
import assert from 'node:assert/strict';
import { build } from 'esbuild';
import { fileURLToPath } from 'node:url';

const root = fileURLToPath(new URL('../../../', import.meta.url));
const bundled = await build({ stdin: { resolveDir: root, contents: "export * from './apps/playground/build/ai/command-schema.ts';" }, bundle: true, platform: 'node', format: 'esm', write: false });
const { commandSchemas, normalizeCommands, validateSchema } = await import(`data:text/javascript;base64,${Buffer.from(bundled.outputFiles[0].text).toString('base64')}`);
const { strict } = commandSchemas(root, 'slide');
const dereference = value => value.$ref ? dereference(strict.$defs[value.$ref.split('/').at(-1)]) : value;
const command = dereference(strict.items).anyOf.map(dereference).find(value => value.properties.type.enum?.[0] === 'element.update');
const patch = dereference(command.properties.patch);
const branches = patch.anyOf?.map(dereference) ?? [];
const wirePatch = (schema, values) => Object.fromEntries(Object.keys(schema.properties).map(key => [key, values[key] ?? null]));
const update = patchValue => ({ type: 'element.update', slideId: 'page', elementId: 'target', patch: patchValue });

test('slide updates expose separate closed text, shape and image patch schemas', () => {
  assert.equal(branches.length, 3);
  const text = branches.find(value => 'color' in value.properties);
  const shape = branches.find(value => 'shape' in value.properties);
  const image = branches.find(value => 'src' in value.properties);
  assert.ok(text && shape && image);
  assert.equal('shape' in text.properties, false);
  assert.equal('src' in text.properties, false);
  assert.equal('color' in shape.properties, false);
  assert.equal('src' in shape.properties, false);
  assert.equal('fontSize' in image.properties, false);
  for (const branch of branches) {
    assert.equal(branch.additionalProperties, false);
    assert.deepEqual(branch.required.sort(), Object.keys(branch.properties).sort());
  }
});

test('strict patches retain only requested edits when decoded, for every element type', () => {
  for (const [selector, values] of [
    ['color', { height: 40, color: '#63DBC7', fontSize: 17 }],
    ['shape', { height: 80, textColor: '#FFFFFF', shape: 'rect' }],
    ['src', { width: 120, alt: '説明' }],
  ]) {
    const branch = branches.find(value => selector in value.properties);
    assert.ok(branch);
    const input = [update(wirePatch(branch, values))];
    validateSchema(input, strict);
    assert.deepEqual(normalizeCommands(root, 'slide', input), [update(values)]);
  }
});

test('mixed element fields from the live failed repair cannot be generated by the strict schema', () => {
  const text = branches.find(value => 'color' in value.properties);
  assert.ok(text);
  const mixed = wirePatch(text, { height: 40, fontSize: 17, color: '#63DBC7' });
  Object.assign(mixed, { shape: 'rect', stroke: '#63DBC7', strokeWidth: 1, textColor: '#FFFFFF', src: '', alt: '' });
  assert.throws(() => validateSchema([update(mixed)], strict));
  assert.throws(() => normalizeCommands(root, 'slide', [update(mixed)]));
});

test('strict patches expose native font, opacity and stroke bounds before model execution', () => {
  const text = branches.find(value => 'color' in value.properties);
  const shape = branches.find(value => 'shape' in value.properties);
  for (const [branch, values] of [[text, { fontSize: 0 }], [text, { fontSize: 1001 }], [text, { opacity: 1.1 }], [shape, { strokeWidth: 101 }]]) {
    assert.throws(() => validateSchema([update(wirePatch(branch, values))], strict));
  }
  for (const [branch, values] of [[text, { fontSize: 1, opacity: 0 }], [text, { fontSize: 1000, opacity: 1 }], [shape, { strokeWidth: 0 }]]) {
    validateSchema([update(wirePatch(branch, values))], strict);
  }
});

test('union constraints are still checked after a nullable numeric branch matches', () => {
  const schema = { anyOf: [{ type: 'number' }, { type: 'null' }], minimum: 1, maximum: 200 };
  for (const value of [null, 1, 200]) validateSchema(value, schema);
  for (const value of [0, 201]) assert.throws(() => validateSchema(value, schema));
});
