import test from 'node:test';
import assert from 'node:assert/strict';
import {build} from 'esbuild';
const output=await build({stdin:{contents:`export {createDocumentDragFeedback} from './src/ui/document-drag-feedback';`,resolveDir:new URL('../',import.meta.url).pathname},bundle:true,platform:'node',format:'esm',write:false});
const {createDocumentDragFeedback}=await import(`data:text/javascript;base64,${Buffer.from(output.outputFiles[0].text).toString('base64')}`);
function fixture(){const win=new EventTarget(),frames=new Map(),timers=new Map();let serial=0;Object.assign(win,{innerWidth:900,innerHeight:600,requestAnimationFrame(fn){const id=++serial;frames.set(id,fn);return id;},cancelAnimationFrame(id){frames.delete(id);},setTimeout(fn){const id=++serial;timers.set(id,fn);return id;},clearTimeout(id){timers.delete(id);}});const children=[];const doc={defaultView:win,body:{append(...nodes){children.push(...nodes);}},createElement(){return {style:{},setAttribute(){},remove(){const index=children.indexOf(this);if(index>=0)children.splice(index,1);}}}};const viewport={ownerDocument:doc,isConnected:true,scrollTop:0,scrollLeft:0,getBoundingClientRect:()=>({left:20,top:20,right:500,bottom:400,width:480,height:380})},classes=new Set();const dom=Object.assign(new EventTarget(),{ownerDocument:doc,closest:selector=>selector==='.lxd-document-viewport'?viewport:null,contains:node=>node===dom,classList:{add:name=>classes.add(name),remove:name=>classes.delete(name)}});let model={id:'initial'};const subscriptions=new Set(),editor={document:model,editable:true,features:{text:true,images:true},session:{getSnapshot:()=>({document:model}),subscribe(fn){subscriptions.add(fn);return()=>subscriptions.delete(fn);}}};const view={dom,dragging:null,state:{selection:{$from:{nodeAfter:null},from:1,to:6},doc:{textBetween:()=>'<hello>',resolve:()=>({depth:1,before:()=>0})}},posAtCoords:()=>({pos:1}),coordsAtPos:()=>({left:40,top:50,bottom:75}),nodeDOM:()=>({getBoundingClientRect:()=>({left:40,top:45,bottom:95,width:300})})};
  // This is deliberately installed before the enhancement, as EditorView does.
  dom.addEventListener('dragstart',event=>{event.dataTransfer.clearData();event.dataTransfer.setData('text/html','<p>hello</p>');view.dragging={slice:'native slice'};});
  const feedback=createDocumentDragFeedback(view,()=>editor);const data=new Map();const transfer={clearData(){data.clear();},setData(key,value){data.set(key,value);},getData:key=>data.get(key)||'',setDragImage(element,x,y){this.image={element,x,y};}};
  const emit=(target,type,props={})=>{const event=new Event(type,{cancelable:true});Object.assign(event,props);target.dispatchEvent(event);return event;};
  const start=()=>emit(dom,'dragstart',{clientX:100,clientY:100,dataTransfer:transfer});
  return {win,frames,timers,children,classes,editor,view,feedback,transfer,data,viewport,subscriptions,start,emit,replace(){model={id:'external'};subscriptions.forEach(fn=>fn());},tick(){const callbacks=[...frames.values()];frames.clear();callbacks.forEach(fn=>fn(100));}};
}
test('document adds a compact native preview after PM serialization, scrolls and preserves native drop handling',()=>{const f=fixture();f.start();assert.equal(f.data.get('text/html'),'<p>hello</p>');assert.ok(f.data.get('application/x-likex-document-drag'));assert.equal(f.transfer.image.element.style.width,'180px');assert.equal(f.transfer.image.element.textContent,'<hello>');assert.equal(f.transfer.image.element.style.opacity,'.72');assert.ok(f.classes.has('lxd-is-dragging'));f.emit(f.win,'dragover',{clientX:540,clientY:430});f.tick();assert.ok(f.viewport.scrollTop>0&&f.viewport.scrollLeft>0);const caret=f.children.find(node=>node.className==='lxd-drag-caret');assert.equal(caret.style.display,'block');const nativeSlice=f.view.dragging;const event=new Event('drop',{cancelable:true});Object.assign(event,{dataTransfer:f.transfer});assert.equal(f.feedback.drop(event),false,'native PM drop is still responsible for the transaction');assert.equal(f.view.dragging,nativeSlice);assert.equal(f.children.length,0);assert.equal(f.frames.size,0);assert.equal(f.timers.size,0);f.feedback.destroy();assert.equal(f.subscriptions.size,0);});
test('image drag uses a horizontal insertion indicator and Escape blocks a stale drop',()=>{const f=fixture();f.view.state.selection.$from.nodeAfter={type:{name:'image'}};f.start();assert.equal(f.transfer.image.element.textContent,'画像');f.emit(f.win,'dragover',{clientX:150,clientY:90});const caret=f.children.find(node=>node.className==='lxd-drag-caret');assert.equal(caret.style.height,'3px');assert.equal(caret.style.width,'300px');f.emit(f.win,'keydown',{key:'Escape'});assert.equal(f.view.dragging,null);assert.equal(f.children.length,0);const event=new Event('drop',{cancelable:true});Object.assign(event,{dataTransfer:f.transfer});assert.equal(f.feedback.drop(event),true);assert.equal(event.defaultPrevented,true);f.feedback.destroy();});
test('model change cancels immediately before React rerender; permission revocation and unmount clean up',()=>{const f=fixture();f.start();f.replace();assert.equal(f.children.length,0);assert.equal(f.view.dragging,null);assert.equal(f.frames.size,0);f.start();f.editor.features.text=false;f.feedback.check();assert.equal(f.children.length,0);f.editor.features.text=true;f.start();f.feedback.destroy();assert.equal(f.frames.size,0);assert.equal(f.children.length,0);assert.equal(f.subscriptions.size,0);f.start();assert.equal(f.children.length,0,'destroy removes the native dragstart listener');});
test('readonly or disabled image operations cannot begin a native drag',()=>{for(const kind of ['readonly','images']){const f=fixture();if(kind==='readonly')f.editor.editable=false;else{f.editor.features.images=false;f.view.state.selection.$from.nodeAfter={type:{name:'image'}};}const event=f.start();assert.equal(event.defaultPrevented,true);assert.equal(f.children.length,0);assert.equal(f.view.dragging,null);f.feedback.destroy();}});
