/** Shared by the evaluator, picker and Excel export. Examples are editable formulas. */
export const SUPPORTED_SPREADSHEET_FUNCTIONS = Object.freeze([
  { name: "SUM", label: "合計", syntax: "SUM(値1, [値2], …)", example: "=SUM(10,20,30)", description: "数値の合計を求めます。", category: "集計" },
  { name: "AVERAGE", label: "平均", syntax: "AVERAGE(値1, [値2], …)", example: "=AVERAGE(10,20,30)", description: "数値の平均を求めます。空のセルは含めません。", category: "集計" },
  { name: "MIN", label: "最小値", syntax: "MIN(値1, [値2], …)", example: "=MIN(10,20,30)", description: "数値の最小値を求めます。", category: "集計" },
  { name: "MAX", label: "最大値", syntax: "MAX(値1, [値2], …)", example: "=MAX(10,20,30)", description: "数値の最大値を求めます。", category: "集計" },
  { name: "COUNT", label: "数値の個数", syntax: "COUNT(値1, [値2], …)", example: "=COUNT(10,20,30)", description: "数値が入っているセルや引数の個数を数えます。", category: "集計" },
  { name: "COUNTA", label: "空でない値の個数", syntax: "COUNTA(値1, [値2], …)", example: "=COUNTA(10,20,30)", description: "文字や論理値、空文字を返す数式も含めて数えます。", category: "集計" },
  { name: "COUNTBLANK", label: "空白の個数", syntax: "COUNTBLANK(範囲)", example: "=COUNTBLANK(B1:B3)", description: "空のセルと空文字を返す数式を数えます。0は含めません。", category: "集計" },
  { name: "COUNTIF", label: "条件に合う個数", syntax: "COUNTIF(範囲, 条件)", example: "=COUNTIF(B1:B3,\">0\")", description: "条件に合うセルを数えます。比較演算子と *・?・~ に対応します。", category: "条件付き集計" },
  { name: "SUMIF", label: "条件に合う合計", syntax: "SUMIF(範囲, 条件, [合計範囲])", example: "=SUMIF(B1:B3,\">0\",C1:C3)", description: "条件に合う数値を合計します。範囲は同じ行数・列数で指定します。", category: "条件付き集計" },
  { name: "AVERAGEIF", label: "条件に合う平均", syntax: "AVERAGEIF(範囲, 条件, [平均範囲])", example: "=IFERROR(AVERAGEIF(B1:B3,\">0\",C1:C3),0)", description: "条件に合う数値の平均を求めます。該当する数値がない場合は #DIV/0!。", category: "条件付き集計" },
  { name: "COUNTIFS", label: "複数条件の個数", syntax: "COUNTIFS(条件範囲1, 条件1, [条件範囲2, 条件2], …)", example: "=COUNTIFS(B1:B3,\">0\",C1:C3,\"完了\")", description: "すべての条件に合うセルの個数です。各範囲の形をそろえます。", category: "条件付き集計" },
  { name: "SUMIFS", label: "複数条件の合計", syntax: "SUMIFS(合計範囲, 条件範囲1, 条件1, …)", example: "=SUMIFS(C1:C3,B1:B3,\"完了\")", description: "すべての条件に合う数値を合計します。", category: "条件付き集計" },
  { name: "AVERAGEIFS", label: "複数条件の平均", syntax: "AVERAGEIFS(平均範囲, 条件範囲1, 条件1, …)", example: "=IFERROR(AVERAGEIFS(C1:C3,B1:B3,\"完了\"),0)", description: "すべての条件に合う数値の平均です。該当する数値がない場合は #DIV/0!。", category: "条件付き集計" },
  { name: "ROUND", label: "四捨五入", syntax: "ROUND(数値, 桁数)", example: "=ROUND(12.345,2)", description: "指定した桁数に四捨五入します。負の桁数では整数部を丸めます。", category: "数値" },
  { name: "ROUNDUP", label: "切り上げ", syntax: "ROUNDUP(数値, 桁数)", example: "=ROUNDUP(-12.341,2)", description: "0から遠ざかる方向へ、指定した桁数で丸めます。", category: "数値" },
  { name: "ROUNDDOWN", label: "切り捨て", syntax: "ROUNDDOWN(数値, 桁数)", example: "=ROUNDDOWN(-12.349,2)", description: "0に近づく方向へ、指定した桁数で丸めます。", category: "数値" },
  { name: "ABS", label: "絶対値", syntax: "ABS(数値)", example: "=ABS(-10)", description: "数値の符号を除いた絶対値を求めます。", category: "数値" },
  { name: "INT", label: "整数への切り下げ", syntax: "INT(数値)", example: "=INT(-1.2)", description: "指定した数値以下の最大の整数を返します。", category: "数値" },
  { name: "MOD", label: "余り", syntax: "MOD(数値, 除数)", example: "=MOD(10,3)", description: "除算の余りを返します。符号は除数にそろいます。", category: "数値" },
  { name: "PRODUCT", label: "積", syntax: "PRODUCT(値1, [値2], …)", example: "=PRODUCT(2,3,4)", description: "数値を掛け合わせます。参照範囲の文字・空白・論理値は除きます。", category: "数値" },
  { name: "IF", label: "条件分岐", syntax: "IF(条件, 真の場合, [偽の場合])", example: '=IF(10>=5,"達成","未達成")', description: "条件に合う場合と合わない場合で値を切り替えます。", category: "論理・判定" },
  { name: "IFERROR", label: "エラー時の値", syntax: "IFERROR(値, エラー時の値)", example: "=IFERROR(1/0,0)", description: "通常の計算エラーを別の値に置き換えます。計算上限や循環参照は除きます。", category: "論理・判定" },
  { name: "IFNA", label: "該当なし時の値", syntax: "IFNA(値, 該当なし時の値)", example: "=IFNA(#N/A,\"未一致\")", description: "#N/A だけを別の値に置き換えます。", category: "論理・判定" },
  { name: "IFS", label: "複数の条件分岐", syntax: "IFS(条件1, 値1, [条件2, 値2], …)", example: "=IFS(10>20,\"大\",10>5,\"中\",TRUE,\"小\")", description: "最初に真になる条件の値を返します。該当しなければ #N/A。", category: "論理・判定" },
  { name: "AND", label: "すべての条件", syntax: "AND(条件1, [条件2], …)", example: "=AND(10>=5,20>=10)", description: "すべての条件が真かどうかを調べます。", category: "論理・判定" },
  { name: "OR", label: "いずれかの条件", syntax: "OR(条件1, [条件2], …)", example: "=OR(10>=5,20>=30)", description: "いずれかの条件が真かどうかを調べます。", category: "論理・判定" },
  { name: "NOT", label: "条件の反転", syntax: "NOT(条件)", example: "=NOT(10>=5)", description: "条件の真と偽を反転します。", category: "論理・判定" },
  { name: "ISBLANK", label: "空のセルか", syntax: "ISBLANK(値)", example: "=ISBLANK(B1)", description: "実際に空のセルなら真。空文字を返す数式は空のセルと区別します。", category: "論理・判定" },
  { name: "ISNUMBER", label: "数値か", syntax: "ISNUMBER(値)", example: "=ISNUMBER(123)", description: "数値なら真。数値の文字列は変換せず判定します。", category: "論理・判定" },
  { name: "ISTEXT", label: "文字列か", syntax: "ISTEXT(値)", example: "=ISTEXT(\"123\")", description: "文字列なら真。空のセルは含めません。", category: "論理・判定" },
  { name: "ISERROR", label: "エラーか", syntax: "ISERROR(値)", example: "=ISERROR(1/0)", description: "通常の計算エラーなら真。循環参照や計算上限は隠しません。", category: "論理・判定" },
  { name: "LEN", label: "文字数", syntax: "LEN(文字列)", example: "=LEN(12345)", description: "空白を含む文字数を求めます。", category: "文字列" },
  { name: "CONCAT", label: "文字列の結合", syntax: "CONCAT(文字列1, [文字列2], …)", example: '=CONCAT("Like","X")', description: "文字列やセル範囲の値を順番に結合します。", category: "文字列" },
  { name: "LEFT", label: "左から取り出す", syntax: "LEFT(文字列, [文字数])", example: "=LEFT(\"LikeX\",4)", description: "左端から指定した文字数を取り出します。省略時は1文字。", category: "文字列" },
  { name: "RIGHT", label: "右から取り出す", syntax: "RIGHT(文字列, [文字数])", example: "=RIGHT(\"LikeX\",1)", description: "右端から指定した文字数を取り出します。省略時は1文字。", category: "文字列" },
  { name: "MID", label: "途中から取り出す", syntax: "MID(文字列, 開始位置, 文字数)", example: "=MID(\"LikeX\",2,3)", description: "1から始まる位置を指定し、文字列の一部を取り出します。", category: "文字列" },
  { name: "TRIM", label: "余分な空白の削除", syntax: "TRIM(文字列)", example: "=TRIM(\"  Like  X  \")", description: "前後の半角スペースを除き、連続した半角スペースを1個にします。", category: "文字列" },
  { name: "UPPER", label: "大文字へ", syntax: "UPPER(文字列)", example: "=UPPER(\"LikeX\")", description: "英字を大文字に変換します。", category: "文字列" },
  { name: "LOWER", label: "小文字へ", syntax: "LOWER(文字列)", example: "=LOWER(\"LikeX\")", description: "英字を小文字に変換します。", category: "文字列" },
  { name: "SUBSTITUTE", label: "文字列を置換", syntax: "SUBSTITUTE(文字列, 検索文字列, 置換文字列, [置換対象])", example: "=SUBSTITUTE(\"a-b-a\",\"a\",\"x\",2)", description: "一致する文字列を置換します。任意で何番目だけを置き換えるか指定できます。", category: "文字列" },
  { name: "FIND", label: "文字の位置", syntax: "FIND(検索文字列, 対象文字列, [開始位置])", example: "=FIND(\"X\",\"LikeX\")", description: "大文字小文字を区別し、1から始まる位置を返します。", category: "文字列" },
  { name: "SEARCH", label: "文字の位置・あいまい検索", syntax: "SEARCH(検索文字列, 対象文字列, [開始位置])", example: "=SEARCH(\"x\",\"LikeX\")", description: "大文字小文字を区別せず検索します。*・?・~ に対応します。", category: "文字列" },
  { name: "TEXTJOIN", label: "区切って結合", syntax: "TEXTJOIN(区切り文字, 空白を無視, 文字列1, [文字列2], …)", example: "=TEXTJOIN(\", \",TRUE,\"Like\",\"X\")", description: "範囲や文字列を区切り文字で結合します。空白を含めるか指定できます。", category: "文字列" },
  { name: "VALUE", label: "文字列を数値へ", syntax: "VALUE(文字列)", example: "=VALUE(\"12.5\")", description: "符号・小数点・指数を含む数値文字列を変換します。通貨や日付の文字列は対象外です。", category: "文字列" },
  { name: "INDEX", label: "指定位置の値", syntax: "INDEX(範囲, 行番号, [列番号])", example: "=INDEX(B1:C3,2,1)", description: "範囲内の単一セルを返します。行・列の配列を返す形式は対象外です。", category: "検索・参照" },
  { name: "MATCH", label: "一致位置", syntax: "MATCH(検索値, 範囲, [照合の種類])", example: "=IFERROR(MATCH(\"完了\",B1:B3,0),0)", description: "1行または1列の範囲で位置を検索します。0は完全一致、1/-1は整列済み範囲の近似一致。", category: "検索・参照" },
  { name: "VLOOKUP", label: "縦の表を検索", syntax: "VLOOKUP(検索値, 表範囲, 列番号, [近似一致])", example: "=IFERROR(VLOOKUP(\"完了\",B1:C3,2,FALSE),\"未一致\")", description: "左端列で検索して指定列の値を返します。FALSEは完全一致、省略時は近似一致。", category: "検索・参照" },
  { name: "HLOOKUP", label: "横の表を検索", syntax: "HLOOKUP(検索値, 表範囲, 行番号, [近似一致])", example: "=IFERROR(HLOOKUP(\"完了\",B1:D2,2,FALSE),\"未一致\")", description: "最上段で検索して指定行の値を返します。FALSEは完全一致、省略時は近似一致。", category: "検索・参照" },
  { name: "XLOOKUP", label: "範囲を検索", syntax: "XLOOKUP(検索値, 検索範囲, 戻り範囲, [未一致時], [一致モード], [検索方向])", example: "=XLOOKUP(\"完了\",B1:B3,C1:C3,\"未一致\")", description: "単一列・行の検索と単一値の取得。完全・近似・ワイルドカード一致、前方/後方の線形検索に対応します。", category: "検索・参照" },
  { name: "ROW", label: "行番号", syntax: "ROW([参照])", example: "=ROW()", description: "式を入力したセル、または指定範囲の左上の行番号を1から返します。", category: "検索・参照" },
  { name: "COLUMN", label: "列番号", syntax: "COLUMN([参照])", example: "=COLUMN()", description: "式を入力したセル、または指定範囲の左上の列番号を1から返します。", category: "検索・参照" },
  { name: "ROWS", label: "行数", syntax: "ROWS(範囲)", example: "=ROWS(B1:C3)", description: "参照範囲の行数を返します。", category: "検索・参照" },
  { name: "COLUMNS", label: "列数", syntax: "COLUMNS(範囲)", example: "=COLUMNS(B1:C3)", description: "参照範囲の列数を返します。", category: "検索・参照" },
  { name: "DATE", label: "日付を組み立てる", syntax: "DATE(年, 月, 日)", example: "=DATE(2026,9,15)", description: "1900日付システムのシリアル値を返します。日付表示形式と組み合わせます。", category: "日付" },
  { name: "YEAR", label: "年", syntax: "YEAR(日付シリアル値)", example: "=YEAR(DATE(2026,9,15))", description: "日付シリアル値から年を取り出します。", category: "日付" },
  { name: "MONTH", label: "月", syntax: "MONTH(日付シリアル値)", example: "=MONTH(DATE(2026,9,15))", description: "日付シリアル値から月を取り出します。", category: "日付" },
  { name: "DAY", label: "日", syntax: "DAY(日付シリアル値)", example: "=DAY(DATE(2026,9,15))", description: "日付シリアル値から日を取り出します。", category: "日付" },
] as const);

export type SpreadsheetFunctionName = typeof SUPPORTED_SPREADSHEET_FUNCTIONS[number]["name"];
export type SpreadsheetFunctionCategory = typeof SUPPORTED_SPREADSHEET_FUNCTIONS[number]["category"];
