"use client";
import { useEffect, useImperativeHandle, useRef, useState, type CSSProperties, type FormEvent, type MouseEvent } from "react";
import { Columns3, Plus, Search, Save, Undo2, Redo2, MoreHorizontal, CalendarDays, GripVertical, Tag, Users, Trash2, Download, Upload } from "lucide-react";
import { openContextMenu, type ContextMenuAction } from "./browser";
import type { BoardProps } from "./props";
import { BOARD_LIMITS, getCard, getCards, parseBoard, serializeBoard, type BoardCard, type BoardColumn } from "./model";
import { useEditor } from "./state/use-editor";
import { Modal } from "./ui/modal";
import { useBoardDrag } from "./ui/use-board-drag";
import "./styles.css";

type CardDraft = Omit<BoardCard, "id"> & { id?: string; columnId: string };
type ColumnDraft = { id?: string; title: string; color: string };
export function LikeBoard({ ref, ...props }: BoardProps) {
  const editor = useEditor(props), board = editor.model, { controller, features } = editor;
  const [query, setQuery] = useState(""), [labelId, setLabelId] = useState(""), [assigneeId, setAssigneeId] = useState("");
  const [card, setCard] = useState<CardDraft | null>(null), [column, setColumn] = useState<ColumnDraft | null>(null), [metadata, setMetadata] = useState<"labels" | "members" | null>(null);
  const [metadataName, setMetadataName] = useState(""), [metadataColor, setMetadataColor] = useState("#3b82f6"), [visible, setVisible] = useState<Record<string, number>>({});
  const [removeColumn, setRemoveColumn] = useState<BoardColumn | null>(null);
  const upload = useRef<HTMLInputElement>(null), closeMenu = useRef<(() => void) | null>(null);
  useEffect(() => () => { closeMenu.current?.(); closeMenu.current = null; }, [board, features, editor.readOnly, editor.busy]);
  function showMenu(event: MouseEvent<HTMLElement>, items: ContextMenuAction[]) {
    const target = event.target as HTMLElement;
    if (event.defaultPrevented || target.closest?.("input,textarea,select,[contenteditable]:not([contenteditable='false'])") || target.ownerDocument?.getSelection?.()?.isCollapsed === false || !items.length) return;
    event.preventDefault(); event.stopPropagation(); closeMenu.current?.();
    const source = controller.getModel();
    closeMenu.current = openContextMenu({ anchor: event.currentTarget, x: event.clientX, y: event.clientY,
      items: items.map(item => ({ ...item, onSelect: () => { if (controller.getModel() === source) return item.onSelect(); } })),
      onError: cause => controller.setNotice({ kind: "error", text: cause instanceof Error ? cause.message : "操作できませんでした。" }),
    });
  }
  function cardMenu(event: MouseEvent<HTMLElement>, cardId: string) {
    const source = controller.getModel(), located = getCard(source, cardId); if (!located) return;
    const current = controller.getSnapshot(), value = located.card, items: ContextMenuAction[] = [
      { id: "card.open", label: "カードの詳細", onSelect: () => openCard(value, located.columnId) },
    ];
    const canCopy = features.cards && (!value.labelIds.length || features.labels) && (!value.assigneeIds.length || features.members);
    if (canCopy) items.push({ id: "card.duplicate", label: "カードを複製", disabled: !current.editable, onSelect: () => controller.execute({ type: "card.add", columnId: located.columnId, index: located.index + 1, card: { ...value, id: crypto.randomUUID(), title: `${value.title.slice(0, 490)}のコピー` } }) });
    if (features.cards && features.move) {
      const columnIndex = source.columns.findIndex(item => item.id === located.columnId), col = source.columns[columnIndex];
      items.push({ id: "card.up", label: "上に移動", disabled: !current.editable || located.index === 0, onSelect: () => controller.execute({ type: "card.move", cardId, columnId: col.id, index: located.index - 1 }) },
        { id: "card.down", label: "下に移動", disabled: !current.editable || located.index === col.cards.length - 1, onSelect: () => controller.execute({ type: "card.move", cardId, columnId: col.id, index: located.index + 1 }) });
      for (const [offset, label] of [[-1, "左の列へ移動"], [1, "右の列へ移動"]] as const) {
        const destination = source.columns[columnIndex + offset];
        items.push({ id: `card.move.${offset}`, label, disabled: !current.editable || !destination, onSelect: () => destination && controller.execute({ type: "card.move", cardId, columnId: destination.id }) });
      }
    }
    if (features.cards) items.push({ id: "card.delete", label: "カードを削除", danger: true, separatorBefore: true, disabled: !current.editable, onSelect: () => controller.execute({ type: "card.delete", cardId }) });
    showMenu(event, items);
  }
  function columnMenu(event: MouseEvent<HTMLElement>, columnId: string) {
    const source = controller.getModel(), index = source.columns.findIndex(item => item.id === columnId), value = source.columns[index]; if (!value) return;
    const current = controller.getSnapshot(), items: ContextMenuAction[] = [];
    if (features.cards) items.push({ id: "card.add", label: "カードを追加", disabled: !current.editable, onSelect: () => { if (controller.getSnapshot().editable && controller.getSnapshot().features.cards) newCard(columnId); } });
    if (features.columns) {
      items.push({ id: "column.edit", label: "列を編集", disabled: !current.editable, onSelect: () => { if (controller.getSnapshot().editable && controller.getSnapshot().features.columns) setColumn({ id: value.id, title: value.title, color: value.color }); } });
      const canCopy = (!value.cards.length || features.cards) && (!value.cards.some(item => item.labelIds.length) || features.labels) && (!value.cards.some(item => item.assigneeIds.length) || features.members);
      if (canCopy) items.push({ id: "column.duplicate", label: "列を複製", disabled: !current.editable, onSelect: () => controller.execute({ type: "column.add", index: index + 1, column: { ...value, id: crypto.randomUUID(), title: `${value.title.slice(0, 190)}のコピー`, cards: value.cards.map(item => ({ ...item, id: crypto.randomUUID() })) } }) });
      if (features.move) items.push({ id: "column.left", label: "列を左に移動", disabled: !current.editable || index === 0, onSelect: () => controller.execute({ type: "column.move", columnId, index: index - 1 }) }, { id: "column.right", label: "列を右に移動", disabled: !current.editable || index === source.columns.length - 1, onSelect: () => controller.execute({ type: "column.move", columnId, index: index + 1 }) });
      if (features.cards) items.push({ id: "column.delete", label: "列を削除", danger: true, separatorBefore: true, disabled: !current.editable, onSelect: () => { if (controller.getSnapshot().editable && controller.getSnapshot().features.columns && controller.getSnapshot().features.cards) setRemoveColumn(value); } });
    }
    showMenu(event, items);
  }
  function boardMenu(event: MouseEvent<HTMLElement>) {
    const current = controller.getSnapshot(), items: ContextMenuAction[] = [];
    if (features.columns) items.push({ id: "column.add", label: "列を追加", disabled: !current.editable, onSelect: () => { if (controller.getSnapshot().editable && controller.getSnapshot().features.columns) setColumn({ title: "", color: "#64748b" }); } });
    if (features.history) items.push({ id: "history.undo", label: "元に戻す", disabled: !current.editable || !current.canUndo, onSelect: controller.undo }, { id: "history.redo", label: "やり直す", disabled: !current.editable || !current.canRedo, onSelect: controller.redo });
    showMenu(event, items);
  }
  const { viewportRef, start: startDrag, drop: dropDrag, target: dropTarget, draggedId } = useBoardDrag({ board, editable: editor.editable, cards: features.cards, columns: features.columns, move: features.move, execute: controller.execute });
  const activeLabel = board.labels.some(label => label.id === labelId) ? labelId : "", activeAssignee = board.members.some(member => member.id === assigneeId) ? assigneeId : "";
  const visibleIds = new Set(getCards(board, { query, labelId: activeLabel || undefined, assigneeId: activeAssignee || undefined }).map(item => item.card.id));
  const iconProps = { size: 16, strokeWidth: 1.7 };
  const nativeImport = (input: string | Blob) => controller.prepare(async (_model, context) => { if (typeof input !== "string" && input.size > BOARD_LIMITS.jsonLength) throw new Error("16 MiB以下のJSONを選択してください。"); const text = typeof input === "string" ? input : await input.text(); if (context.signal.aborted) throw new Error("読み込みを中止しました。"); return { type: "board.replace" as const, board: parseBoard(text) }; }, { feature: "import" });
  function exportNative() { const state = controller.getSnapshot(); if (!state.features.export || state.busy) throw new Error("現在は書き出しできません。"); return new Blob([serializeBoard(state.model)], { type: "application/json" }); }
  useImperativeHandle(ref, () => ({ getBoard: controller.getModel, execute: controller.execute, undo: controller.undo, redo: controller.redo, save: controller.save, discard: controller.discard, importNative: nativeImport, exportNative }));
  function download() { try { const blob = exportNative(), url = URL.createObjectURL(blob), link = document.createElement("a"); link.href = url; link.download = `${board.title.replace(/[\\/:*?"<>|]/g, "_") || "board"}.json`; link.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); } catch (cause) { controller.setNotice({ kind: "error", text: cause instanceof Error ? cause.message : "書き出しに失敗しました。" }); } }
  function openCard(value: BoardCard, columnId: string) { const located = getCard(board, value.id)!; if (props.onCardOpen) { props.onCardOpen({ ...located, board }); return; } setCard({ ...value, labelIds: [...value.labelIds], assigneeIds: [...value.assigneeIds], columnId }); }
  function newCard(columnId: string) { setCard({ title: "", description: "", dueDate: null, labelIds: [], assigneeIds: [], columnId }); }
  async function saveCard(event: FormEvent) { event.preventDefault(); if (!card) return; const { id, columnId, ...values } = card; const existing = id ? getCard(controller.getModel(), id) : undefined; const patch = existing ? Object.fromEntries(Object.entries(values).filter(([key, value]) => JSON.stringify(value) !== JSON.stringify(existing.card[key as keyof typeof values]))) : values; const commands = id ? [{ type: "card.update" as const, cardId: id, patch }, ...(existing?.columnId !== columnId ? [{ type: "card.move" as const, cardId: id, columnId }] : [])] : [{ type: "card.add" as const, columnId, card: values }]; if (await controller.execute(commands)) setCard(null); }
  async function saveColumn(event: FormEvent) { event.preventDefault(); if (!column) return; const { id, ...values } = column; if (await controller.execute(id ? { type: "column.update", columnId: id, patch: values } : { type: "column.add", column: values })) setColumn(null); }
  const style = { "--lxb-primary": editor.palette.primary, "--lxb-on-primary": editor.palette.onPrimary, "--lxb-accent": editor.palette.accent, "--lxb-selection": editor.palette.selection, ...props.style } as CSSProperties;
  return <div data-likex-board="" data-color-mode={editor.dark ? "dark" : "light"} className={`lxb-root ${props.className ?? ""}`} style={style} aria-label={props["aria-label"] ?? "ボード"} onKeyDown={event => { if (!(event.ctrlKey || event.metaKey) || (event.target as HTMLElement).closest("input,textarea,select")) return; if (event.key.toLowerCase() === "z" && features.history) { event.preventDefault(); void (event.shiftKey ? controller.redo() : controller.undo()); } if (event.key.toLowerCase() === "s") { event.preventDefault(); void controller.save(); } }}>
    <header className="lxb-header"><Columns3 size={21} /><strong>{props.title ?? board.title}</strong><span>LikeBoard</span>{features.history && <div className="lxb-history"><button type="button" title="元に戻す" aria-label="元に戻す" disabled={!editor.editable || !editor.canUndo} onClick={() => void controller.undo()}><Undo2 {...iconProps} /></button><button type="button" title="やり直す" aria-label="やり直す" disabled={!editor.editable || !editor.canRedo} onClick={() => void controller.redo()}><Redo2 {...iconProps} /></button></div>}{!editor.readOnly && <button type="button" className="lxb-save" disabled={!editor.editable || !editor.dirty} onClick={() => void controller.save()}><Save {...iconProps} />{editor.busy === "save" ? "保存中…" : "保存"}</button>}</header>
    <nav className="lxb-toolbar" aria-label="ボード操作"><span className="lxb-view-tab"><Columns3 {...iconProps} />ボード</span><div className="lxb-search"><Search {...iconProps} /><input aria-label="カードを検索" placeholder="カードを検索" value={query} onChange={event => setQuery(event.target.value)} /></div><select aria-label="ラベルで絞り込み" value={activeLabel} onChange={event => setLabelId(event.target.value)}><option value="">すべてのラベル</option>{board.labels.map(label => <option key={label.id} value={label.id}>{label.name}</option>)}</select><select aria-label="担当者で絞り込み" value={activeAssignee} onChange={event => setAssigneeId(event.target.value)}><option value="">すべての担当者</option>{board.members.map(member => <option key={member.id} value={member.id}>{member.name}</option>)}</select><div className="lxb-toolbar-spacer" />
      {features.labels && !editor.readOnly && <button type="button" disabled={!editor.editable} title="ラベルの管理" onClick={() => setMetadata("labels")}><Tag {...iconProps} />ラベル</button>}{features.members && !editor.readOnly && <button type="button" disabled={!editor.editable} title="メンバーの管理" onClick={() => setMetadata("members")}><Users {...iconProps} />メンバー</button>}
      {(features.import || features.export) && <details className="lxb-menu"><summary>ファイル</summary><div>{features.import && !editor.readOnly && <button type="button" disabled={!editor.editable} onClick={() => upload.current?.click()}><Upload {...iconProps} />JSONを開く</button>}{features.export && <button type="button" disabled={!!editor.busy} onClick={download}><Download {...iconProps} />JSONを書き出す</button>}</div></details>}
    </nav>
    <input ref={upload} type="file" hidden accept=".json,application/json" onChange={event => { const file = event.target.files?.[0]; event.target.value = ""; if (file) void nativeImport(file); }} />
    <main ref={viewportRef} className="lxb-board" aria-label="列とカード" onDrop={dropDrag} onContextMenu={boardMenu}>{board.columns.map((col, columnIndex) => { const cards = col.cards.filter(card => visibleIds.has(card.id)), shown = cards.slice(0, visible[col.id] ?? 100); return <section className="lxb-column" key={col.id} aria-label={col.title} data-lxb-column={col.id} onContextMenu={event => columnMenu(event, col.id)} data-dragging={draggedId === col.id || undefined} data-drop-column={dropTarget?.kind === "column" && dropTarget.anchorId === col.id ? dropTarget.edge : undefined}>
      <header className="lxb-column-header"><button type="button" className="lxb-grip" aria-label={`${col.title}をドラッグして移動`} disabled={!editor.editable || !features.columns || !features.move} draggable={editor.editable && features.columns && features.move} onDragStart={event => startDrag(event, { kind: "column", id: col.id, title: col.title })}><GripVertical size={15} /></button><i style={{ background: col.color }} /><h2>{col.title}</h2><span className="lxb-count">{cards.length}</span>{features.columns && !editor.readOnly && <details className="lxb-menu"><summary aria-label={`${col.title}の操作`}><MoreHorizontal {...iconProps} /></summary><div><button type="button" disabled={!editor.editable} onClick={() => setColumn({ id: col.id, title: col.title, color: col.color })}>列を編集</button>{features.move && <><button type="button" disabled={!editor.editable || columnIndex === 0} onClick={() => void controller.execute({ type: "column.move", columnId: col.id, index: columnIndex - 1 })}>左に移動</button><button type="button" disabled={!editor.editable || columnIndex === board.columns.length - 1} onClick={() => void controller.execute({ type: "column.move", columnId: col.id, index: columnIndex + 1 })}>右に移動</button></>}<button type="button" disabled={!editor.editable || !features.cards} onClick={() => setRemoveColumn(col)}>列を削除</button></div></details>}</header>
      <div className="lxb-card-list" data-empty-drop={dropTarget?.kind === "card" && dropTarget.columnId === col.id && !dropTarget.anchorId || undefined}>{shown.map(value => <article key={value.id} className="lxb-card" data-lxb-card={value.id} onContextMenu={event => cardMenu(event, value.id)} data-dragging={draggedId === value.id || undefined} data-drop-card={dropTarget?.kind === "card" && dropTarget.anchorId === value.id ? dropTarget.edge : undefined} tabIndex={0} role="button" aria-label={value.title} draggable={editor.editable && features.cards && features.move} onDragStart={event => startDrag(event, { kind: "card", id: value.id, title: value.title })} onClick={() => openCard(value, col.id)} onKeyDown={event => { if (event.key === "Enter" || event.key === " ") { event.preventDefault(); openCard(value, col.id); } if (event.altKey && features.move && features.cards && ["ArrowLeft", "ArrowRight", "ArrowUp", "ArrowDown"].includes(event.key)) { event.preventDefault(); const index = col.cards.indexOf(value), horizontal = event.key === "ArrowLeft" || event.key === "ArrowRight", target = horizontal ? board.columns[columnIndex + (event.key === "ArrowLeft" ? -1 : 1)] : col; if (target) void controller.execute({ type: "card.move", cardId: value.id, columnId: target.id, ...(horizontal ? {} : { index: Math.max(0, Math.min(col.cards.length - 1, index + (event.key === "ArrowUp" ? -1 : 1))) }) }); } }}>
        {value.labelIds.length > 0 && <div className="lxb-labels">{value.labelIds.map(id => { const label = board.labels.find(label => label.id === id)!; return <span key={id} style={{ background: `color-mix(in srgb, ${label.color} 18%, var(--lxb-surface))`, borderColor: label.color }}>{label.name}</span>; })}</div>}<h3>{value.title}</h3>{value.description && <p>{value.description}</p>}<footer>{value.dueDate && <span className="lxb-date"><CalendarDays size={13} />{value.dueDate.slice(5).replace("-", "/")}</span>}<div className="lxb-assignees">{value.assigneeIds.map(id => { const member = board.members.find(member => member.id === id)!; return <span key={id} title={member.name}>{member.name.slice(0, 1)}</span>; })}</div></footer>
      </article>)}{cards.length > shown.length && <button type="button" className="lxb-add-card" onClick={() => setVisible({ ...visible, [col.id]: shown.length + 100 })}>さらに100件を表示</button>}</div>{features.cards && !editor.readOnly && <button type="button" className="lxb-add-card" disabled={!editor.editable} onClick={() => newCard(col.id)}><Plus size={16} />カードを追加</button>}
    </section>; })}{features.columns && !editor.readOnly && <button type="button" className="lxb-add-column" disabled={!editor.editable} onClick={() => setColumn({ title: "", color: "#64748b" })}><Plus size={17} />列を追加</button>}</main>
    <footer className="lxb-status"><span>{board.columns.length} 列 · {getCards(board).length} カード</span>{editor.notice && <span role={editor.notice.kind === "error" ? "alert" : "status"} className={`lxb-notice-${editor.notice.kind}`}>{editor.notice.text}</span>}{editor.busy && <span role="status">処理中…</span>}</footer>
    {card && <Modal title={card.id ? "カードの詳細" : "新しいカード"} onClose={() => setCard(null)}><form onSubmit={event => void saveCard(event)}><label>タイトル<input required maxLength={500} value={card.title} readOnly={!editor.editable || !features.cards} onChange={event => setCard({ ...card, title: event.target.value })} /></label><label>説明<textarea rows={5} value={card.description} readOnly={!editor.editable || !features.cards} onChange={event => setCard({ ...card, description: event.target.value })} /></label><div className="lxb-form-row"><label>列<select value={card.columnId} disabled={!editor.editable || !features.move || !features.cards} onChange={event => setCard({ ...card, columnId: event.target.value })}>{board.columns.map(col => <option key={col.id} value={col.id}>{col.title}</option>)}</select></label><label>期日<input type="date" value={card.dueDate ?? ""} readOnly={!editor.editable || !features.cards} onChange={event => setCard({ ...card, dueDate: event.target.value || null })} /></label></div><fieldset disabled={!editor.editable || !features.cards || !features.labels}><legend>ラベル</legend>{board.labels.length ? board.labels.map(label => <label className="lxb-check" key={label.id}><input type="checkbox" checked={card.labelIds.includes(label.id)} onChange={event => setCard({ ...card, labelIds: event.target.checked ? [...card.labelIds, label.id] : card.labelIds.filter(id => id !== label.id) })} />{label.name}</label>) : <small>ラベルはまだありません。</small>}</fieldset><fieldset disabled={!editor.editable || !features.cards || !features.members}><legend>担当者</legend>{board.members.length ? board.members.map(member => <label className="lxb-check" key={member.id}><input type="checkbox" checked={card.assigneeIds.includes(member.id)} onChange={event => setCard({ ...card, assigneeIds: event.target.checked ? [...card.assigneeIds, member.id] : card.assigneeIds.filter(id => id !== member.id) })} />{member.name}</label>) : <small>メンバーはまだ登録されていません。</small>}</fieldset><div className="lxb-dialog-actions">{card.id && features.cards && !editor.readOnly && <button type="button" className="lxb-danger" disabled={!editor.editable} onClick={() => void controller.execute({ type: "card.delete", cardId: card.id! }).then(result => { if (result) setCard(null); })}><Trash2 size={15} />削除</button>}<span /><button type="button" onClick={() => setCard(null)}>閉じる</button>{features.cards && !editor.readOnly && <button type="submit" className="lxb-primary" disabled={!editor.editable}>{card.id ? "変更を適用" : "追加"}</button>}</div></form></Modal>}
    {column && features.columns && <Modal title={column.id ? "列を編集" : "列を追加"} onClose={() => setColumn(null)}><form onSubmit={event => void saveColumn(event)}><label>列の名前<input required maxLength={200} value={column.title} onChange={event => setColumn({ ...column, title: event.target.value })} /></label><label>色<input type="color" value={column.color} onChange={event => setColumn({ ...column, color: event.target.value })} /></label><div className="lxb-dialog-actions"><span /><button type="button" onClick={() => setColumn(null)}>キャンセル</button><button type="submit" className="lxb-primary" disabled={!editor.editable}>適用</button></div></form></Modal>}
    {removeColumn && features.columns && features.cards && <Modal title="列を削除しますか？" onClose={() => setRemoveColumn(null)}><p>「{removeColumn.title}」と、その中の{removeColumn.cards.length}件のカードを削除します。元に戻す操作で復元できます。</p><div className="lxb-dialog-actions"><span /><button type="button" onClick={() => setRemoveColumn(null)}>キャンセル</button><button type="button" className="lxb-danger" disabled={!editor.editable} onClick={() => void controller.execute({ type: "column.delete", columnId: removeColumn.id }).then(result => { if (result) setRemoveColumn(null); })}>削除</button></div></Modal>}
    {metadata && features[metadata] && <Modal title={metadata === "labels" ? "ラベルの管理" : "メンバーの管理"} onClose={() => setMetadata(null)}><div className="lxb-metadata-list">{(metadata === "labels" ? board.labels : board.members).map(item => <div key={item.id}><span>{"color" in item && <i style={{ background: String(item.color) }} />}{item.name}</span><button type="button" aria-label={`${item.name}を削除`} disabled={!editor.editable} onClick={() => void controller.execute(metadata === "labels" ? { type: "label.delete", labelId: item.id } : { type: "member.delete", memberId: item.id })}><Trash2 size={15} /></button></div>)}</div><form onSubmit={event => { event.preventDefault(); void controller.execute(metadata === "labels" ? { type: "label.add", label: { name: metadataName, color: metadataColor } } : { type: "member.add", member: { name: metadataName } }).then(result => { if (result) setMetadataName(""); }); }}><label>名前<input required maxLength={100} value={metadataName} onChange={event => setMetadataName(event.target.value)} /></label>{metadata === "labels" && <label>色<input type="color" value={metadataColor} onChange={event => setMetadataColor(event.target.value)} /></label>}<div className="lxb-dialog-actions"><span /><button type="submit" className="lxb-primary" disabled={!editor.editable}>追加</button></div></form></Modal>}
  </div>;
}
export default LikeBoard;
