import assert from 'node:assert/strict';
import { readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import postcss from 'postcss';
import tailwind from '@tailwindcss/postcss';
import { packageRoot, sourceRoot } from './lib/run.mjs';
import { installedPackage } from './lib/packages.mjs';
import { scopeExplorerStyles } from './lib/explorer-styles.mjs';

export async function buildStyles({ check = false } = {}) {
  const inputFile = path.join(packageRoot, 'styles/input.css');
  const outputFile = path.join(sourceRoot, 'styles.css');
  const input = await readFile(inputFile, 'utf8');
  const compiled = await postcss([tailwind({ base: packageRoot, optimize: false })])
    .process(input, { from: inputFile, map: false });
  const { directory } = await installedPackage('tailwindcss');
  const license = (await readFile(path.join(directory, 'LICENSE'), 'utf8')).trim();
  const css = '/* Generated by npm run build:styles. Edit styles/input.css or src TS/TSX, then rebuild. */\n' +
    `/*! Bundled Tailwind CSS license:\n${license}\n*/\n` + scopeExplorerStyles(compiled.css);
  let previous;
  try { previous = await readFile(outputFile, 'utf8'); }
  catch (error) { if (error.code !== 'ENOENT') throw error; }
  if (check) assert.ok(previous === css, 'Explorer styles are stale. Run npm run build:styles and include src/styles.css.');
  else if (previous !== css) await writeFile(outputFile, css);
  return { css, outputFile, changed: previous !== css };
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const { css, changed } = await buildStyles({ check: process.argv.includes('--check') });
  console.log(`Explorer CSS ${process.argv.includes('--check') ? 'is current' : changed ? 'generated' : 'unchanged'}: ${Buffer.byteLength(css)} bytes`);
}
