"use client";
import { useEffect, useImperativeHandle, useRef, useState, type CSSProperties, type FormEvent, type MouseEvent } from "react";
import { Database, Plus, Search, Save, Undo2, Redo2, SlidersHorizontal, MoreHorizontal, ArrowUpDown, Layers, Eye, Expand, Trash2, ChevronLeft, ChevronRight, Download, Upload, Type, Hash, CalendarDays, CheckSquare, ListFilter } from "lucide-react";
import { openContextMenu, type ContextMenuAction } from "./browser";
import type { DataViewProps } from "./props";
import { DATAVIEW_LIMITS, exportDataViewCsv, importDataViewCsv, parseDataView, serializeDataView, queryDataViewRows, groupDataViewRows, type DataViewField, type DataViewFieldType, type DataViewQuery, type DataViewValue } from "./model";
import { useEditor } from "./state/use-editor";
import { Modal } from "./ui/modal";
import "./styles.css";

const typeNames: Record<DataViewFieldType, string> = { text: "テキスト", number: "数値", date: "日付", boolean: "チェックボックス", select: "選択肢" };
const icons = { text: Type, number: Hash, date: CalendarDays, boolean: CheckSquare, select: ListFilter };
function ValueInput({ field, value, disabled, onValue, multiline = false }: { field: DataViewField; value: DataViewValue; disabled: boolean; onValue(value: DataViewValue): void; multiline?: boolean }) {
  if (field.type === "boolean") return <input type="checkbox" aria-label={field.name} checked={value === true} disabled={disabled} onChange={event => onValue(event.target.checked)} />;
  if (field.type === "select") return <select aria-label={field.name} value={String(value ?? "")} disabled={disabled} onChange={event => onValue(event.target.value || null)}><option value="">未設定</option>{field.options.map(option => <option key={option}>{option}</option>)}</select>;
  const commit = (source: string) => onValue(field.type === "number" ? source.trim() === "" ? null : Number(source) : field.type === "date" ? source || null : source);
  if (multiline && field.type === "text") return <textarea key={String(value)} aria-label={field.name} defaultValue={String(value ?? "")} readOnly={disabled} rows={3} onBlur={event => commit(event.target.value)} />;
  return <input key={`${field.type}:${String(value)}`} aria-label={field.name} type={field.type === "number" ? "number" : field.type === "date" ? "date" : "text"} step={field.type === "number" ? "any" : undefined} defaultValue={String(value ?? "")} readOnly={disabled} onBlur={event => commit(event.target.value)} onKeyDown={event => { if (event.key === "Enter") event.currentTarget.blur(); if (event.key === "Escape") { event.currentTarget.value = String(value ?? ""); event.currentTarget.blur(); } }} />;
}
export function LikeDataView({ ref, ...props }: DataViewProps) {
  const editor = useEditor(props), data = editor.model, { controller, features } = editor;
  const [query, updateQuery] = useState<DataViewQuery>(() => structuredClone(props.initialQuery ?? {})), [page, setPage] = useState(0);
  const [fieldDraft, setFieldDraft] = useState<{ id?: string; name: string; type: DataViewFieldType; options: string } | null>(null);
  const [rowDraft, setRowDraft] = useState<{ id?: string; values: Record<string, DataViewValue> } | null>(null), [removeField, setRemoveField] = useState<DataViewField | null>(null);
  const [panel, setPanel] = useState<"sort" | "filter" | "group" | "columns" | null>(null);
  const closeMenu = useRef<(() => void) | null>(null);
  useEffect(() => () => { closeMenu.current?.(); closeMenu.current = null; }, [data, features, editor.readOnly, editor.busy, query]);
  const upload = useRef<HTMLInputElement>(null), uploadKind = useRef<"json" | "csv">("json");
  const known = new Set(data.fields.map(field => field.id));
  const effectiveQuery: DataViewQuery = { search: features.filter ? query.search : undefined, filters: features.filter ? query.filters?.filter(filter => known.has(filter.fieldId)) : undefined, sort: features.sort ? query.sort?.filter(sort => known.has(sort.fieldId)) : undefined, groupBy: features.group && query.groupBy && known.has(query.groupBy) ? query.groupBy : undefined, hiddenFieldIds: features.columnVisibility ? query.hiddenFieldIds?.filter(id => known.has(id)) : undefined };
  const rows = queryDataViewRows(data, effectiveQuery), pageCount = Math.max(1, Math.ceil(rows.length / 50)), currentPage = Math.min(page, pageCount - 1), pageIds = new Set(rows.slice(currentPage * 50, currentPage * 50 + 50).map(row => row.id));
  const rowNumbers = new Map(rows.map((row, index) => [row.id, index + 1]));
  const groups = groupDataViewRows(data, effectiveQuery).map(group => ({ ...group, rows: group.rows.filter(row => pageIds.has(row.id)) })).filter(group => group.rows.length);
  const fields = data.fields.filter(field => !effectiveQuery.hiddenFieldIds?.includes(field.id));
  function setQuery(next: DataViewQuery) { try { if (!features.sort && next.sort?.length || !features.filter && (next.search || next.filters?.length) || !features.group && next.groupBy || !features.columnVisibility && next.hiddenFieldIds?.length) throw new Error("この表示機能は無効です。"); queryDataViewRows(controller.getModel(), next); const copy = structuredClone(next); updateQuery(copy); setPage(0); props.onQueryChange?.(structuredClone(copy)); } catch (cause) { controller.setNotice({ kind: "error", text: cause instanceof Error ? cause.message : "表示条件が正しくありません。" }); } }
  const nativeImport = (input: string | Blob, kind: "json" | "csv" = "json") => controller.prepare(async (_model, context) => { if (typeof input !== "string" && input.size > DATAVIEW_LIMITS.jsonLength) throw new Error("32 MiB以下のファイルを選択してください。"); const source = typeof input === "string" ? input : await input.text(); if (context.signal.aborted) throw new Error("読み込みを中止しました。"); return { type: "data.replace" as const, data: kind === "json" ? parseDataView(source) : importDataViewCsv(source) }; }, { feature: "import" });
  function exportBlob(kind: "json" | "csv") { const snapshot = controller.getSnapshot(); if (!snapshot.features.export || snapshot.busy) throw new Error("現在は書き出しできません。"); return new Blob([kind === "csv" ? "\uFEFF" + exportDataViewCsv(snapshot.model) : serializeDataView(snapshot.model)], { type: kind === "csv" ? "text/csv;charset=utf-8" : "application/json" }); }
  useImperativeHandle(ref, () => ({ getData: controller.getModel, execute: controller.execute, undo: controller.undo, redo: controller.redo, save: controller.save, discard: controller.discard, importNative: input => nativeImport(input), importCsv: input => nativeImport(input, "csv"), exportNative: () => exportBlob("json"), exportCsv: () => exportBlob("csv"), getQuery: () => structuredClone(effectiveQuery), setQuery }));
  function download(kind: "json" | "csv") { try { const blob = exportBlob(kind), url = URL.createObjectURL(blob), link = document.createElement("a"); link.href = url; link.download = `${data.title.replace(/[\\/:*?"<>|]/g, "_") || "data"}.${kind}`; link.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); } catch (cause) { controller.setNotice({ kind: "error", text: cause instanceof Error ? cause.message : "書き出しに失敗しました。" }); } }
  function requestUpload(kind: "json" | "csv") { uploadKind.current = kind; if (upload.current) { upload.current.accept = kind === "json" ? ".json,application/json" : ".csv,text/csv"; upload.current.click(); } }
  function openRow(id: string) { const row = data.rows.find(row => row.id === id)!; if (props.onRowOpen) props.onRowOpen({ row, data }); else setRowDraft({ id, values: { ...row.values } }); }
  async function saveRow(event: FormEvent) { event.preventDefault(); if (!rowDraft) return; const result = await controller.execute(rowDraft.id ? { type: "row.update", rowId: rowDraft.id, values: rowDraft.values } : { type: "row.add", row: { values: rowDraft.values } }); if (result) setRowDraft(null); }
  async function saveField(event: FormEvent) { event.preventDefault(); if (!fieldDraft) return; const values = { name: fieldDraft.name, type: fieldDraft.type, options: fieldDraft.type === "select" ? fieldDraft.options.split(/\r?\n/).map(option => option.trim()).filter(Boolean) : [] }; const existing = fieldDraft.id ? controller.getModel().fields.find(field => field.id === fieldDraft.id) : undefined; const patch = existing ? Object.fromEntries(Object.entries(values).filter(([key, value]) => JSON.stringify(value) !== JSON.stringify(existing[key as keyof typeof values]))) : values; if (existing && Object.keys(patch).length === 0) { setFieldDraft(null); return; } if (await controller.execute(fieldDraft.id ? { type: "field.update", fieldId: fieldDraft.id, patch } : { type: "field.add", field: values })) setFieldDraft(null); }
  function showMenu(event: MouseEvent<HTMLElement>, items: ContextMenuAction[]) {
    const target = event.target as HTMLElement;
    if (event.defaultPrevented || target.closest?.("input,textarea,select,[contenteditable]:not([contenteditable='false'])") || target.ownerDocument?.getSelection?.()?.isCollapsed === false || !items.length) return;
    event.preventDefault(); event.stopPropagation(); closeMenu.current?.();
    const source = controller.getModel();
    closeMenu.current = openContextMenu({ anchor: event.currentTarget, x: event.clientX, y: event.clientY,
      items: items.map(item => ({ ...item, onSelect: () => { if (controller.getModel() === source) return item.onSelect(); } })),
      onError: cause => controller.setNotice({ kind: "error", text: cause instanceof Error ? cause.message : "操作できませんでした。" }),
    });
  }
  function rowMenu(event: MouseEvent<HTMLElement>, rowId: string, fieldId?: string) {
    const source = controller.getModel(), row = source.rows.find(item => item.id === rowId); if (!row) return;
    const current = controller.getSnapshot(), items: ContextMenuAction[] = [{ id: "row.open", label: "レコードの詳細", onSelect: () => openRow(rowId) }];
    if (fieldId && features.editCells) items.push({ id: "cell.clear", label: "セルをクリア", disabled: !current.editable || row.values[fieldId] === null, onSelect: () => controller.execute({ type: "cell.set", rowId, fieldId, value: null }) });
    if (features.rows) items.push({ id: "row.duplicate", label: "レコードを複製", disabled: !current.editable, onSelect: () => controller.execute({ type: "row.add", index: source.rows.indexOf(row) + 1, row: { values: { ...row.values } } }) },
      { id: "row.delete", label: "レコードを削除", danger: true, separatorBefore: true, disabled: !current.editable, onSelect: () => controller.execute({ type: "row.delete", rowId }) });
    showMenu(event, items);
  }
  function fieldMenu(event: MouseEvent<HTMLElement>, fieldId: string) {
    const source = controller.getModel(), index = source.fields.findIndex(item => item.id === fieldId), field = source.fields[index]; if (!field) return;
    const current = controller.getSnapshot(), items: ContextMenuAction[] = [];
    if (features.fields) {
      items.push({ id: "field.edit", label: "フィールドを編集", disabled: !current.editable, onSelect: () => { if (controller.getSnapshot().editable && controller.getSnapshot().features.fields) setFieldDraft({ ...field, options: field.options.join("\n") }); } },
        { id: "field.left", label: "左に移動", disabled: !current.editable || index === 0, onSelect: () => controller.execute({ type: "field.move", fieldId, index: index - 1 }) },
        { id: "field.right", label: "右に移動", disabled: !current.editable || index === source.fields.length - 1, onSelect: () => controller.execute({ type: "field.move", fieldId, index: index + 1 }) });
    }
    if (features.sort) items.push({ id: "field.sort.asc", label: "昇順で並べ替え", separatorBefore: items.length > 0, onSelect: () => { if (controller.getSnapshot().features.sort) setQuery({ ...query, sort: [{ fieldId, direction: "asc" }] }); } },
      { id: "field.sort.desc", label: "降順で並べ替え", onSelect: () => { if (controller.getSnapshot().features.sort) setQuery({ ...query, sort: [{ fieldId, direction: "desc" }] }); } });
    if (features.group) items.push({ id: "field.group", label: effectiveQuery.groupBy === fieldId ? "グループ化を解除" : "このフィールドでグループ化", onSelect: () => { if (controller.getSnapshot().features.group) setQuery({ ...query, groupBy: effectiveQuery.groupBy === fieldId ? null : fieldId }); } });
    if (features.columnVisibility) items.push({ id: "field.hide", label: "フィールドを非表示", onSelect: () => { if (controller.getSnapshot().features.columnVisibility) setQuery({ ...query, hiddenFieldIds: [...(query.hiddenFieldIds ?? []), fieldId] }); } });
    if (features.fields && features.editCells) items.push({ id: "field.delete", label: "フィールドを削除", danger: true, separatorBefore: true, disabled: !current.editable, onSelect: () => { if (controller.getSnapshot().editable && controller.getSnapshot().features.fields && controller.getSnapshot().features.editCells) setRemoveField(field); } });
    showMenu(event, items);
  }
  function gridMenu(event: MouseEvent<HTMLElement>) {
    const current = controller.getSnapshot(), items: ContextMenuAction[] = [];
    if (features.rows) items.push({ id: "row.add", label: "レコードを追加", disabled: !current.editable, onSelect: () => { if (controller.getSnapshot().editable && controller.getSnapshot().features.rows) setRowDraft({ values: Object.fromEntries(controller.getModel().fields.map(field => [field.id, null])) }); } });
    if (features.fields) items.push({ id: "field.add", label: "フィールドを追加", disabled: !current.editable, onSelect: () => { if (controller.getSnapshot().editable && controller.getSnapshot().features.fields) setFieldDraft({ name: "", type: "text", options: "" }); } });
    if (features.history) items.push({ id: "history.undo", label: "元に戻す", separatorBefore: items.length > 0, disabled: !current.editable || !current.canUndo, onSelect: controller.undo }, { id: "history.redo", label: "やり直す", disabled: !current.editable || !current.canRedo, onSelect: controller.redo });
    showMenu(event, items);
  }
  const style = { "--lxv-primary": editor.palette.primary, "--lxv-on-primary": editor.palette.onPrimary, "--lxv-accent": editor.palette.accent, "--lxv-selection": editor.palette.selection, ...props.style } as CSSProperties;
  return <div data-likex-dataview="" data-color-mode={editor.dark ? "dark" : "light"} className={`lxv-root ${props.className ?? ""}`} style={style} aria-label={props["aria-label"] ?? "データビュー"} onKeyDown={event => { if (!(event.ctrlKey || event.metaKey) || (event.target as HTMLElement).closest("input,textarea,select")) return; if (event.key.toLowerCase() === "z" && features.history) { event.preventDefault(); void (event.shiftKey ? controller.redo() : controller.undo()); } if (event.key.toLowerCase() === "s") { event.preventDefault(); void controller.save(); } }}>
    <header className="lxv-header"><Database size={20} /><strong>{props.title ?? data.title}</strong><span>LikeDataView</span>{features.history && <div className="lxv-history"><button type="button" title="元に戻す" aria-label="元に戻す" disabled={!editor.editable || !editor.canUndo} onClick={() => void controller.undo()}><Undo2 size={16} /></button><button type="button" title="やり直す" aria-label="やり直す" disabled={!editor.editable || !editor.canRedo} onClick={() => void controller.redo()}><Redo2 size={16} /></button></div>}{!editor.readOnly && <button type="button" className="lxv-save" disabled={!editor.editable || !editor.dirty} onClick={() => void controller.save()}><Save size={16} />{editor.busy === "save" ? "保存中…" : "保存"}</button>}</header>
    <nav className="lxv-toolbar" aria-label="データ操作"><span className="lxv-view-tab"><Database size={16} />グリッド</span>{features.filter && <><div className="lxv-search"><Search size={15} /><input aria-label="レコードを検索" placeholder="レコードを検索" value={query.search ?? ""} onChange={event => setQuery({ ...query, search: event.target.value })} /></div><button type="button" className={effectiveQuery.filters?.length ? "is-active" : ""} onClick={() => setPanel(panel === "filter" ? null : "filter")}><SlidersHorizontal size={15} />フィルター</button></>}{features.sort && <button type="button" className={effectiveQuery.sort?.length ? "is-active" : ""} onClick={() => setPanel(panel === "sort" ? null : "sort")}><ArrowUpDown size={15} />並べ替え</button>}{features.group && <button type="button" className={effectiveQuery.groupBy ? "is-active" : ""} onClick={() => setPanel(panel === "group" ? null : "group")}><Layers size={15} />グループ</button>}{features.columnVisibility && <button type="button" onClick={() => setPanel(panel === "columns" ? null : "columns")}><Eye size={15} />表示列</button>}<div className="lxv-toolbar-spacer" />{features.rows && !editor.readOnly && <button type="button" className="lxv-primary" disabled={!editor.editable} onClick={() => setRowDraft({ values: Object.fromEntries(data.fields.map(field => [field.id, null])) })}><Plus size={15} />レコード追加</button>}{(features.import || features.export) && <details className="lxv-menu"><summary>ファイル</summary><div>{features.import && !editor.readOnly && <><button type="button" disabled={!editor.editable} onClick={() => requestUpload("json")}><Upload size={14} />JSONを開く</button><button type="button" disabled={!editor.editable} onClick={() => requestUpload("csv")}><Upload size={14} />CSVを開く</button></>}{features.export && ["json", "csv"].map(kind => <button type="button" key={kind} disabled={!!editor.busy} onClick={() => download(kind as "json" | "csv")}><Download size={14} />{kind.toUpperCase()}を書き出す</button>)}</div></details>}</nav>
    <input ref={upload} type="file" hidden onChange={event => { const file = event.target.files?.[0]; event.target.value = ""; if (file) void nativeImport(file, uploadKind.current); }} />
    {panel && features[panel === "columns" ? "columnVisibility" : panel] && <div className="lxv-view-options">{panel === "sort" && <><label>並べ替える列<select aria-label="並べ替える列" value={effectiveQuery.sort?.[0]?.fieldId ?? ""} onChange={event => setQuery({ ...query, sort: event.target.value ? [{ fieldId: event.target.value, direction: "asc" }] : [] })}><option value="">指定なし</option>{data.fields.map(field => <option key={field.id} value={field.id}>{field.name}</option>)}</select></label><label>順序<select aria-label="並べ替え順" value={effectiveQuery.sort?.[0]?.direction ?? "asc"} disabled={!effectiveQuery.sort?.length} onChange={event => setQuery({ ...query, sort: [{ fieldId: effectiveQuery.sort![0].fieldId, direction: event.target.value as "asc" | "desc" }] })}><option value="asc">昇順</option><option value="desc">降順</option></select></label></>}{panel === "group" && <label>グループの列<select aria-label="グループの列" value={effectiveQuery.groupBy ?? ""} onChange={event => setQuery({ ...query, groupBy: event.target.value || null })}><option value="">グループ化しない</option>{data.fields.map(field => <option key={field.id} value={field.id}>{field.name}</option>)}</select></label>}{panel === "columns" && data.fields.map(field => <label className="lxv-check" key={field.id}><input type="checkbox" checked={!effectiveQuery.hiddenFieldIds?.includes(field.id)} onChange={event => setQuery({ ...query, hiddenFieldIds: event.target.checked ? (query.hiddenFieldIds ?? []).filter(id => id !== field.id) : [...(query.hiddenFieldIds ?? []), field.id] })} />{field.name}</label>)}{panel === "filter" && <><label>対象列<select aria-label="絞り込む列" value={effectiveQuery.filters?.[0]?.fieldId ?? ""} onChange={event => setQuery({ ...query, filters: event.target.value ? [{ fieldId: event.target.value, operator: "contains", value: "" }] : [] })}><option value="">指定なし</option>{data.fields.map(field => <option key={field.id} value={field.id}>{field.name}</option>)}</select></label>{effectiveQuery.filters?.[0] && <><label>条件<select aria-label="絞り込み条件" value={effectiveQuery.filters[0].operator} onChange={event => setQuery({ ...query, filters: [{ ...effectiveQuery.filters![0], operator: event.target.value as "contains" | "isEmpty" }] })}><option value="contains">含む</option><option value="isEmpty">未設定</option></select></label>{effectiveQuery.filters[0].operator !== "isEmpty" && <label>値<input aria-label="絞り込む値" value={String(effectiveQuery.filters[0].value ?? "")} onChange={event => setQuery({ ...query, filters: [{ ...effectiveQuery.filters![0], value: event.target.value }] })} /></label>}</>}</>}<button type="button" className="lxv-option-close" aria-label="表示設定を閉じる" onClick={() => setPanel(null)}>×</button></div>}
    <main className="lxv-grid" onContextMenu={gridMenu}><table><thead><tr><th className="lxv-row-number">#</th>{fields.map(field => { const Icon = icons[field.type]; return <th key={field.id} data-lxv-field={field.id} onContextMenu={event => fieldMenu(event, field.id)}><div><Icon size={14} /><span>{field.name}</span>{features.fields && !editor.readOnly && <details className="lxv-menu"><summary aria-label={`${field.name}の操作`}><MoreHorizontal size={15} /></summary><div><button type="button" disabled={!editor.editable} onClick={() => setFieldDraft({ ...field, options: field.options.join("\n") })}>フィールドを編集</button><button type="button" disabled={!editor.editable || !features.editCells} onClick={() => setRemoveField(field)}>フィールドを削除</button><button type="button" disabled={!editor.editable || data.fields.indexOf(field) === 0} onClick={() => void controller.execute({ type: "field.move", fieldId: field.id, index: data.fields.indexOf(field) - 1 })}>左に移動</button><button type="button" disabled={!editor.editable || data.fields.indexOf(field) === data.fields.length - 1} onClick={() => void controller.execute({ type: "field.move", fieldId: field.id, index: data.fields.indexOf(field) + 1 })}>右に移動</button></div></details>}</div></th>; })}<th className="lxv-row-actions">{features.fields && !editor.readOnly && <button type="button" aria-label="フィールドを追加" disabled={!editor.editable} onClick={() => setFieldDraft({ name: "", type: "text", options: "" })}><Plus size={16} /></button>}</th></tr></thead><tbody>{groups.map(group => <GroupRows key={group.key} name={effectiveQuery.groupBy ? group.label : undefined} span={fields.length + 2}>{group.rows.map(row => <tr key={row.id} data-lxv-row={row.id} onContextMenu={event => rowMenu(event, row.id)}><td className="lxv-row-number">{rowNumbers.get(row.id)}</td>{fields.map(field => <td key={field.id} className={`lxv-cell lxv-cell-${field.type}`} onContextMenu={event => rowMenu(event, row.id, field.id)}><ValueInput field={field} value={row.values[field.id]} disabled={!editor.editable || !features.editCells} onValue={value => { if (value !== row.values[field.id]) void controller.execute({ type: "cell.set", rowId: row.id, fieldId: field.id, value }); }} /></td>)}<td className="lxv-row-actions"><button type="button" aria-label={`レコード${rowNumbers.get(row.id)}の詳細`} onClick={() => openRow(row.id)}><Expand size={14} /></button></td></tr>)}</GroupRows>)}</tbody></table>{rows.length === 0 && <div className="lxv-empty"><Database size={28} /><p>{data.rows.length ? "条件に一致するレコードはありません。" : "レコードを追加してデータを整理しましょう。"}</p></div>}</main>
    <footer className="lxv-status"><span>{rows.length} / {data.rows.length} レコード</span>{editor.notice && <span role={editor.notice.kind === "error" ? "alert" : "status"} className={`lxv-notice-${editor.notice.kind}`}>{editor.notice.text}</span>}<div className="lxv-pagination"><button type="button" aria-label="前のページ" disabled={currentPage === 0} onClick={() => setPage(currentPage - 1)}><ChevronLeft size={15} /></button><span>{currentPage + 1} / {pageCount}</span><button type="button" aria-label="次のページ" disabled={currentPage + 1 === pageCount} onClick={() => setPage(currentPage + 1)}><ChevronRight size={15} /></button></div></footer>
    {rowDraft && <Modal title={rowDraft.id ? "レコードの詳細" : "新しいレコード"} onClose={() => setRowDraft(null)}><form onSubmit={event => void saveRow(event)}>{data.fields.map(field => <label key={field.id}>{field.name}<ValueInput multiline field={field} value={rowDraft.values[field.id]} disabled={!editor.editable || (!!rowDraft.id && !features.editCells)} onValue={value => setRowDraft({ ...rowDraft, values: { ...rowDraft.values, [field.id]: value } })} /></label>)}<div className="lxv-dialog-actions">{rowDraft.id && features.rows && !editor.readOnly && <button type="button" className="lxv-danger" disabled={!editor.editable} onClick={() => void controller.execute({ type: "row.delete", rowId: rowDraft.id! }).then(result => { if (result) setRowDraft(null); })}><Trash2 size={15} />削除</button>}<span /><button type="button" onClick={() => setRowDraft(null)}>閉じる</button>{!editor.readOnly && (rowDraft.id ? features.editCells : features.rows) && <button type="submit" className="lxv-primary" disabled={!editor.editable}>{rowDraft.id ? "変更を適用" : "追加"}</button>}</div></form></Modal>}
    {fieldDraft && <Modal title={fieldDraft.id ? "フィールドの設定" : "フィールドを追加"} onClose={() => setFieldDraft(null)}><form onSubmit={event => void saveField(event)}><label>名前<input required value={fieldDraft.name} onChange={event => setFieldDraft({ ...fieldDraft, name: event.target.value })} /></label><label>種類<select value={fieldDraft.type} disabled={!!fieldDraft.id && !features.editCells} onChange={event => setFieldDraft({ ...fieldDraft, type: event.target.value as DataViewFieldType })}>{Object.entries(typeNames).map(([type, label]) => <option key={type} value={type}>{label}</option>)}</select></label>{fieldDraft.type === "select" && <label>選択肢（1行に1つ）<textarea rows={5} readOnly={!!fieldDraft.id && !features.editCells} value={fieldDraft.options} onChange={event => setFieldDraft({ ...fieldDraft, options: event.target.value })} /></label>}{fieldDraft.id && <small>既存の値を新しい種類で扱えない場合、変更は適用されません。</small>}<div className="lxv-dialog-actions"><span /><button type="button" onClick={() => setFieldDraft(null)}>キャンセル</button><button type="submit" className="lxv-primary" disabled={!editor.editable}>適用</button></div></form></Modal>}
    {removeField && <Modal title="フィールドを削除しますか？" onClose={() => setRemoveField(null)}><p>「{removeField.name}」と各レコードの値を削除します。元に戻す操作で復元できます。</p><div className="lxv-dialog-actions"><span /><button type="button" onClick={() => setRemoveField(null)}>キャンセル</button><button type="button" className="lxv-danger" disabled={!editor.editable} onClick={() => void controller.execute({ type: "field.delete", fieldId: removeField.id }).then(result => { if (result) setRemoveField(null); })}>削除</button></div></Modal>}
  </div>;
}
function GroupRows({ name, span, children }: { name?: string; span: number; children: React.ReactNode }) { return <>{name && <tr className="lxv-group"><th colSpan={span}><Layers size={14} />{name}</th></tr>}{children}</>; }
export default LikeDataView;
