import test from 'node:test';
import assert from 'node:assert/strict';
import {build} from 'esbuild';
import {act,createElement as h} from 'react';
import {create} from 'react-test-renderer';
globalThis.IS_REACT_ACT_ENVIRONMENT=true;
const output=await build({stdin:{contents:`export {SlideFilmstrip} from './src/ui/slide-filmstrip';export {SlideCanvas} from './src/ui/slide-canvas';export * from './src/model';`,resolveDir:new URL('../',import.meta.url).pathname},bundle:true,platform:'node',format:'esm',write:false,plugins:[{name:'react',setup(b){b.onResolve({filter:/^(react|react-dom|lucide-react)(\/.*)?$/},({path})=>({path:import.meta.resolve(path),external:true}));}}]});
const {SlideFilmstrip,SlideCanvas,createSlideDeck,createSlideElement,applySlideCommands}=await import(`data:text/javascript;base64,${Buffer.from(output.outputFiles[0].text+'\n//# sourceURL=slide-drag-tests.js').toString('base64')}`);
const change=async fn=>act(async()=>{await fn();});
const pointer=(x,y,extra={})=>({button:0,pointerId:1,clientX:x,clientY:y,shiftKey:false,altKey:false,preventDefault(){},stopPropagation(){},...extra});
function environment(t){const before=globalThis.ResizeObserver;globalThis.ResizeObserver=class{observe(){}disconnect(){}};t.after(()=>{globalThis.ResizeObserver=before;});const win=new EventTarget(),frames=new Map();let serial=0,now=0;Object.assign(win,{innerWidth:1100,innerHeight:800,requestAnimationFrame(callback){const id=++serial;frames.set(id,callback);return id;},cancelAnimationFrame(id){frames.delete(id);}});const doc={defaultView:win};function node(rect={left:0,top:0,right:900,bottom:600,width:900,height:600}){return Object.assign(new EventTarget(),{ownerDocument:doc,isConnected:true,clientWidth:rect.width,clientHeight:rect.height,scrollTop:0,scrollLeft:0,getBoundingClientRect:()=>rect,focus(){},querySelector(){return null;},setPointerCapture(){},hasPointerCapture:()=>false});}return {win,frames,node,tick(){const callbacks=[...frames.values()];frames.clear();callbacks.forEach(callback=>callback(now+=16));},emit(name,extra={}){const event=new Event(name,{cancelable:true});Object.assign(event,extra);win.dispatchEvent(event);}};}
function editorFor(deck){const commands=[];const editor={deck,editable:true,readOnly:false,features:{reorderSlides:true,addSlides:true,deleteSlides:true,formatting:true,text:true},selection:{slideId:deck.slides[0].id,elementIds:[]},select(value){editor.selection=value;},async execute(value){commands.push(value);editor.deck=applySlideCommands(editor.deck,Array.isArray(value)?value:[value]).deck;}};return {editor,commands};}
function deckWithSlides(){return createSlideDeck({slides:['one','two','three','four'].map(id=>({id,name:id,background:'#fff',notes:'',elements:[]}))});}
async function filmstrip(t){const env=environment(t),{editor,commands}=editorFor(deckWithSlides());const root=env.node({left:0,top:0,right:220,bottom:420,width:220,height:420}),list=env.node({left:0,top:32,right:220,bottom:380,width:220,height:348});list.querySelectorAll=()=>editor.deck.slides.map((slide,index)=>({dataset:{filmstripId:slide.id},getBoundingClientRect:()=>({top:40+index*110-list.scrollTop,bottom:140+index*110-list.scrollTop})}));let renderer;const render=()=>h(SlideFilmstrip,{editor});await change(()=>{renderer=create(render(),{createNodeMock:element=>element.type==='aside'?root:element.type==='ol'?list:null});});t.after(()=>change(()=>renderer.unmount()));return {...env,editor,commands,root,list,renderer,refresh:()=>change(()=>renderer.update(render())),async start(id,y){const capture=env.node();capture.querySelector=selector=>{assert.equal(selector,'.lxp-slide-thumbnail');return {focus(options){assert.deepEqual(options,{preventScroll:true});root.focusedId=id;}};};await change(()=>renderer.root.findByProps({'data-filmstrip-id':id}).props.onPointerDown(pointer(80,y,{target:{closest:selector=>selector==='button'||selector==='.lxp-slide-thumbnail'?{}:null},currentTarget:capture})));assert.equal(root.focusedId,id,'dragging must retain keyboard focus for undo');}};}

test('filmstrip uses one model move, source-excluded insertion index, small preview and edge scrolling',async t=>{const f=await filmstrip(t);await f.start('one',90);await change(()=>f.emit('pointermove',pointer(90,260)));assert.equal(f.commands.length,0);assert.equal(f.renderer.root.findAllByProps({className:'lxp-slide-drag-preview'}).length,1);assert.equal(f.renderer.root.findAllByProps({className:'lxp-slide-insertion'}).length,1);await change(()=>f.emit('pointermove',pointer(90,430)));await change(()=>{for(let i=0;i<8;i++)f.tick();});assert.ok(f.list.scrollTop>0);await change(()=>f.emit('pointerup',pointer(90,370)));assert.deepEqual(f.commands,[{type:'slide.move',slideId:'one',index:3}]);assert.deepEqual(f.editor.deck.slides.map(slide=>slide.id),['two','three','four','one']);assert.equal(f.frames.size,0);await f.refresh();f.list.scrollTop=0;await f.start('one',370);await change(()=>f.emit('pointerup',pointer(90,35)));assert.deepEqual(f.editor.deck.slides.map(slide=>slide.id),['one','two','three','four']);assert.equal(f.commands.length,2);});
test('filmstrip cancels on Escape, readonly, external model replacement and unmount',async t=>{const f=await filmstrip(t);await f.start('one',90);await change(()=>f.emit('pointermove',pointer(80,250)));await change(()=>f.emit('keydown',{key:'Escape'}));await change(()=>f.emit('pointerup',pointer(80,250)));assert.equal(f.commands.length,0);assert.equal(f.frames.size,0);await f.start('one',90);f.editor.editable=false;await f.refresh();await change(()=>f.emit('pointerup',pointer(80,250)));assert.equal(f.commands.length,0);f.editor.editable=true;await f.refresh();await f.start('one',90);f.editor.deck=createSlideDeck({title:'external'});await f.refresh();assert.equal(f.frames.size,0);assert.equal(f.commands.length,0);await f.start(f.editor.deck.slides[0].id,90);await change(()=>f.renderer.unmount());assert.equal(f.frames.size,0);});

test('canvas auto-scroll keeps full geometry, commits once and cancels stale gestures',async t=>{const env=environment(t);const deck=createSlideDeck({width:800,height:600,slides:[{id:'slide',name:'one',background:'#fff',notes:'',elements:[createSlideElement({type:'shape',id:'shape',x:50,y:60,width:180,height:100})]}]});const {editor,commands}=editorFor(deck),viewport=env.node(),surface=env.node();let renderer;const render=()=>h(SlideCanvas,{deck:editor.deck,slide:editor.deck.slides[0],editor,zoom:200});await change(()=>{renderer=create(render(),{createNodeMock:element=>element.props.className==='lxp-canvas-viewport'?viewport:element.props.className==='lxp-canvas-surface'?surface:null});});t.after(()=>change(()=>renderer.unmount()));const shape=()=>renderer.root.findByProps({'data-slide-element':'shape'}),canvas=()=>renderer.root.findByProps({className:'lxp-canvas-surface'}),capture=env.node();await change(()=>shape().props.onPointerDown(pointer(100,100,{currentTarget:capture})));await change(()=>canvas().props.onPointerMove(pointer(1000,650)));assert.equal(shape().props.style.opacity,.62);assert.equal(shape().props.style.width,180);assert.equal(commands.length,0);await change(()=>env.tick());assert.ok(viewport.scrollLeft>0&&viewport.scrollTop>0);const previewX=shape().props.style.left;await change(()=>env.emit('pointerup',{pointerId:1,clientX:1040,clientY:690}));assert.equal(commands.length,1);assert.ok(editor.deck.slides[0].elements[0].x>previewX,'release updates coordinates after the last pointermove');assert.equal(editor.deck.slides[0].elements[0].width,180);assert.equal(env.frames.size,0);await change(()=>renderer.update(render()));await change(()=>shape().props.onPointerDown(pointer(100,100,{currentTarget:capture})));await change(()=>canvas().props.onPointerMove(pointer(300,200)));await change(()=>env.emit('keydown',{key:'Escape'}));await change(()=>env.emit('pointerup',{pointerId:1}));assert.equal(commands.length,1);await change(()=>shape().props.onPointerDown(pointer(100,100,{currentTarget:capture})));editor.deck=createSlideDeck({...editor.deck,title:'Updated elsewhere'});await change(()=>renderer.update(render()));await change(()=>env.emit('pointerup',{pointerId:1}));assert.equal(commands.length,1);assert.equal(env.frames.size,0);});

for(const [label,x,y] of [['canvas',300,250],['heading',90,10],['below list',90,430],['outside browser',-10,250]])test(`filmstrip releasing over ${label} cancels instead of committing the nearest insertion`,async t=>{const f=await filmstrip(t);await f.start('one',90);await change(()=>f.emit('pointermove',pointer(x,y)));await change(()=>f.tick());if(y>380)assert.ok(f.list.scrollTop>0,'scrolling outside the list is allowed during the drag');await change(()=>f.emit('pointerup',pointer(x,y)));assert.equal(f.commands.length,0);assert.deepEqual(f.editor.deck.slides.map(slide=>slide.id),['one','two','three','four']);assert.equal(f.frames.size,0);assert.equal(f.renderer.root.findAllByProps({className:'lxp-slide-drag-preview'}).length,0);});
